// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uimzfzysoyaespjtqfya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpbXpmenlzb3lhZXNwanRxZnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Njc0NDAsImV4cCI6MjA2NTI0MzQ0MH0.X9QTEHYBuLnImymAeRvkJgcaCO4ed3S7KAsnV41l2nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);